### ISSUE TITLE
Generated Group is not deleted

### ISSUE THREAD

**Issue by confile** [developertown/integratej2objc#2]
When I execute the following many times the generated Group "generated" is not deleted.
```
integratej2objc integrate_source -p number-incrementer-ios -x NumberIncrementer.xcodeproj -s ../TestJ2Objc/build/j2objc -g generated -t NumberIncrementer
```

Everytime I execute the command a new Group was added.

![numberincrementer_xcodeproj](https://cloud.githubusercontent.com/assets/64265/6065282/3cc31cd2-ad64-11e4-9b50-0c4150f910b1.png)

**Comment by jonnolen** [comment]
Can you post your directory structure and where you running the command from?

**Comment by confile** [comment]
Sure here it is. If I can help you any further please tell me.

![testetest](https://cloud.githubusercontent.com/assets/64265/6087823/5706584c-ae50-11e4-80a1-8ab6aeb47fc0.png)

**Comment by jonnolen** [comment]
you are running the command from `number-incrementer-ios/..`?

**Comment by confile** [comment]
No I run the command from ``Project``folder which is 

```
Project
  /number-increment-ios
 /Test2Objc
```

**Comment by confile** [comment]
``Project`` is the parent folder of ``number-increment-ios`` and ``Test2Objc``

**Comment by jonnolen** [comment]
can you try manually deleting all of your generated groups from the xcode project and then run the command again?  I ran into this as well once, but am unable to replicate it.

**Comment by confile** [comment]
I tried this but everytime the group is duplicated.

**Comment by jonnolen** [comment]
can you try bundle update, and then execute again... i've made some changes that may be fixing the issue for me locally.

**Comment by confile** [comment]
What is bundle update?

**Comment by jonnolen** [comment]
sorry, i updated the installation method.  I think that you have an old version of the gem, if you look at the readme there are instructions for managing the gem installation using bundler.  bundle update forces the newest version of the gem to be pulled from github (using the Gemfile entry in the readme).  then you can run integratej2objc using bundle exec integratej2objc.

**Comment by confile** [comment]
okay I will test it and give you feedback.

**Comment by confile** [comment]
I could not install thee gem from git: 

```
 gem 'integratej2objc', git:'https://github.com/developertown/integratej2objc.git'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command integratej2objc,
```

**Comment by confile** [comment]
I did it with: 

```
git clone https://github.com/developertown/integratej2objc.git
cd integratej2objc/
gem install integratej2objc
```

**Comment by confile** [comment]
Are you sure you pushed the update the gem was updated 4 days ago?

Also I get again a new ``generated`` folder every time I do the command.

**Comment by jonnolen** [comment]
I just completed a small refactor and add test coverage.  I think I found the cause of your problem.  I've updated the documentation for the -g option and the script will now honor groups in place and nested groups:

So for a structure that looks like this:
```
MyProject.xcodeproj
   ↳MyProject
        ↳generated_source 
```

Before the script wasn't finding `generated_source` if you passed in `-g 'generated_source'` because the actual group path is `MyProject/generated_source`, so it wasn't getting removed correctly.  So in this case the correct value for -g is `-g 'MyProject/generated_source'`

Even if you would have passed in the group as a  path before it would have deleted the original group, but it would have failed to create the new groups in the correct place.  

Now if your group is `MyProject/generated_source`  the script will:
1  delete `generated_source` from the `MyProject` group, 
2  then we check each step of the path to re-use or re-create any missing parent group until we get to end group (generated_source), so for a group `MyProject/group1/group2/group3/generated_group`.
   *  check for `MyProject`, use existing or create new,
   *  check `MyProject` group for `group1`, use existing or create new.
   *  check `group1` for `group2`, use existing or create new.
   *  check `group2` for `generated_group`, probably create new since the script deleted it at the beginning.
3  Finally, add all of the files and sub groups to `generated_source` from `--source_root` option.

**Comment by confile** [comment]
I will check it and give you feedback

**Comment by confile** [comment]
@jonnolen I checked your suggestion but it still did not work. My project structure is: 

```
MyProject.xcodeproj
   generated
```
So the command I use is: 

```
integratej2objc integrate_source -p Test111 -x Test111.xcodeproj -s ../TestJ2Objc/build/j2objc -g generated -t Test111
```

And still the ``generated`` folder is created on every call. Could you please post an example how it works correct? 

I also tried 

```
integratej2objc integrate_source -p Test111 -x Test111.xcodeproj -s ../TestJ2Objc/build/j2objc -g Test111/generated -t Test111
```
but this leads to the error:

```
/Library/Ruby/Gems/2.0.0/gems/integratej2objc-0.0.1/bin/integratej2objc:47:in `files_for_group': undefined method `files' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/integratej2objc-0.0.1/bin/integratej2objc:37:in `integrate_source'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/integratej2objc-0.0.1/bin/integratej2objc:107:in `<top (required)>'
	from /usr/bin/integratej2objc:23:in `load'
	from /usr/bin/integratej2objc:23:in `<main>'
```
